---
- name: CDeploy Web Servers on OSP
  hosts: localhost
  connection: local

  tasks:

    - name: Ensure configuration of Security Group is present
      include_role:
        name: osp_securitygroups
        tasks_from: sg_web.yml
      vars:
        securitygroup:
          - name: web-app-sg
            state: present
            description: Security Group for Web Apps
            rules:
              - protocol: tcp
                port: 80
                prefix: 0.0.0.0/0
                state: present
              - protocol: tcp
                port: 22
                prefix: 0.0.0.0/0
                state: present

    - name: Ensure Web instances are presents
      include_role:
        name: osp_provision
        tasks_from: provision.yml
      vars:
        instance_name: "weblxonp0{{ item }}"
        instance_state: present
        os_cloud_name: "{{ keypair_name }}"
        instance_flavor: m1.small
        instance_image: rhel-server-7.4-x86_64
        keypair_name: ""
        instance_meta: "group=apps,deployment_name=PROD"
        instance_network: "net-name=priv-net"
        instance_secgroups: web-app-sg
      with_sequence: count="{{ os_web_count }}"

    - name: Create In Memory Inventory
      include_role:
        name: osp_facts
        tasks_from: main.yml

- name: Ensure Instances are well configured
  hosts: "{{ scope }}"

  tasks:
    - name: Configure Web instances
      include_role:
        name: config.role
        tasks_from: main.yml


  # - name: Deploy app1 instance
  #   include_role:
  #      name: osp_provision
  #      vars_from: app1.yml
  #
  # - name: Create In-Memory Inventory
  #   include_role:
  #      name: osp_facts
