---
- name: CDeploy Web Servers on OSP
  hosts: localhost
  connection: local

  tasks:

    - name: Ensure configuration of Security Group is present
      include_role:
        name: osp_securitygroups
        tasks_from: sg_web.yml
      vars:
        securitygroup:
          - name: web-app-sg
            state: present
            description: Security Group for Web Apps
            rules:
              - protocol: tcp
                port: 80
                prefix: 0.0.0.0/0
                state: present
              - protocol: tcp
                port: 22
                prefix: 0.0.0.0/0
                state: present



  # - name: Deploy app1 instance
  #   include_role:
  #      name: osp_provision
  #      vars_from: app1.yml
  #
  # - name: Create In-Memory Inventory
  #   include_role:
  #      name: osp_facts
