---
# tasks file for ./roles/osp_securitygroups
- name: Ensure {{ item.name }} Security Group is {{ item.state }}
  os_security_group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    cloud: "{{ os_cloud_name }}"
    description: "{{ item.description }}"
  loop: "{{ lookup('dict',securitygroup)}}"

- name: Ensure "{{ item.name }}" Security Groups Rules are {{ item.rules.state }}
  os_security_group_rule:
    state: "{{ item.rules.state }}"
    cloud: "{{ os_cloud_name }}"
    security_group: "{{ item.name }}"
    protocol: "{{ item.rules.protocol }}"
    port_range_min: "{{ item.rules.port }}"
    port_range_max: "{{ item.rules.port }}"
    remote_ip_prefix: "{{ item.rules.prefix }}"
  loop: "{{ lookup('dict',securitygroup)}}"
  # with_items:
  #   - { port: '80', prefix: '0.0.0.0/0' }
  #   - { port: '22', prefix: '0.0.0.0/0' }
  #   - { port: '443', prefix: '0.0.0.0/0' }
