---
# tasks file for osp_facts
- name: Gather Facts from OSP Instances
  os_server_facts:
    cloud: "{{ os_cloud_name }}"
#    region_name: "{{ osp_region_name }}"
  register: result

- name: Add host to in-memory inventory
  add_host:
    name: "{{ item.name }}"
    ansible_host: "{{ item.public_v4 }}"
#    ansible_ssh_user: cloud-user
#    ansible_ssh_private_key_file: "{{ ansible_env.HOME }}/.ssh/{{ keypair_name }}_id_rsa"
    group: "{{ item.metadata.group }},{{item.metadata.environment}}"
  with_items: "{{result.ansible_facts.openstack_servers}}"

- name: Ensure INstances are up and reachable
  wait_for_connection:
    timeout: 600
    sleep : 15
  with_items: "{{result.ansible_facts.openstack_servers.public_v4 }}"

# - name: Register In Memory Inventory for other playbooks
#   set_stats:
#     data:
#       inventory: "{{ inventory }}"
